<?php
/**
 * Created by PhpStorm.
 * User: Arsen
 * Date: 14/06/2017
 * Time: 04:15
 */

namespace frontend\widgets;


use yii\base\Widget;

class Events extends Widget
{

    public function init()
    {
        parent::init();

    }
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}